# Fire-Fighter Pipeline Configuration
# This file documents the pipeline setup for easy recreation

pipeline:
  name: fire-fighter-pipeline
  description: "CI/CD pipeline for Fire-Fighter monorepo - Backend (Spring Boot) + Frontend (Angular/Ionic)"
  
  source:
    repository: "https://github.com/your-username/Fire-Fighter.git"
    credentials: "github-credentials"
    branches:
      - "*/main"
      - "*/develop"
    script_path: "Jenkinsfile"
  
  triggers:
    - github_webhook: true
    - poll_scm: "H/5 * * * *"
  
  build_settings:
    timeout: 30  # minutes
    concurrent_builds: false
    discard_old_builds:
      max_builds: 10
      max_days: 30
  
  environment:
    java_version: "17"
    maven_version: "3.8"
    nodejs_version: "22"
  
  credentials:
    - id: "DB_HOST"
      type: "secret_text"
      description: "Database host"
    - id: "DB_PASSWORD"
      type: "secret_text"
      description: "Database password"
    - id: "JWT_SECRET"
      type: "secret_text"
      description: "JWT secret key"
    - id: "GMAIL_APP_PASSWORD"
      type: "secret_text"
      description: "Gmail app password"
    - id: "GOOGLE_GEMINI_API_KEY"
      type: "secret_text"
      description: "Google Gemini API key"
  
  stages:
    - name: "Checkout"
      description: "Clone repository and set build version"
    - name: "Environment Setup"
      description: "Verify Java, Maven, and Node.js"
    - name: "Install Dependencies"
      description: "Maven and NPM dependency installation"
      parallel: true
    - name: "Code Quality & Linting"
      description: "Code quality checks and linting"
      parallel: true
    - name: "Unit Tests"
      description: "Backend and frontend unit tests"
      parallel: true
    - name: "Build Applications"
      description: "Build JAR and Angular production build"
      parallel: true
    - name: "Integration Tests"
      description: "API integration testing"
      conditions:
        - branch: "main"
        - branch: "develop"
        - change_request: true
    - name: "Security Scan"
      description: "OWASP and NPM security scanning"
      parallel: true
    - name: "Build Mobile App"
      description: "Android APK generation"
      conditions:
        - branch: "main"
        - branch: "release/*"
    - name: "Deploy to Staging"
      description: "Staging environment deployment"
      conditions:
        - branch: "develop"
    - name: "Deploy to Production"
      description: "Production deployment with approval"
      conditions:
        - branch: "main"
      approval_required: true
  
  notifications:
    email:
      recipients:
        - "firefighter.daemon@gmail.com"
      triggers:
        - failure
        - unstable
        - back_to_normal
    
  artifacts:
    - "FF-API/target/*.jar"
    - "FF-Angular/www/**/*"
    - "FF-Angular/android/app/build/outputs/apk/debug/*.apk"
  
  reports:
    - type: "junit"
      pattern: "FF-API/target/surefire-reports/*.xml"
    - type: "coverage"
      pattern: "FF-API/target/site/jacoco/index.html"
    - type: "coverage"
      pattern: "FF-Angular/coverage/index.html"
